// Consumes Rime's word-level timestamps (via CanvasAgent's transcriptionNode
// tap — see canvas-agent.ts) and reports how many complete sentences have
// actually been delivered as audio, not merely generated by the LLM.
//
// Pure TypeScript, no LiveKit imports, so the benchmark harness can drive it
// with a synthetic word stream and no audio at all.

const SENTENCE_TERMINATORS = new Set(['.', '!', '?']);

export interface SpokenWord {
  text: string;
  startTime?: number | undefined;
  endTime?: number | undefined;
}

export class DeliveryTracker {
  // Words accumulated since the last confirmed sentence boundary — not yet "heard".
  private pendingTail = '';
  // Text through the last confirmed sentence boundary — the actual heard text.
  private confirmed = '';
  private deliveredSentences = 0;

  /** Appends a word to the running buffer. Returns the current count of fully-delivered sentences. */
  push(word: SpokenWord): number {
    this.pendingTail += word.text;

    const trimmed = word.text.trimEnd();
    const lastChar = trimmed.at(-1);
    // A sentence counts as delivered only once a terminator token has
    // actually been spoken — an endTime is the evidence audio played for it.
    if (lastChar !== undefined && SENTENCE_TERMINATORS.has(lastChar) && word.endTime !== undefined) {
      this.confirmed += this.pendingTail;
      this.pendingTail = '';
      this.deliveredSentences += 1;
    }

    return this.deliveredSentences;
  }

  /** Everything delivered so far, through the last confirmed sentence boundary — the heard text. */
  get deliveredText(): string {
    return this.confirmed;
  }

  get sentenceCount(): number {
    return this.deliveredSentences;
  }

  reset(): void {
    this.pendingTail = '';
    this.confirmed = '';
    this.deliveredSentences = 0;
  }
}
